# Generated by Django 2.2.2 on 2020-02-21 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200221_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.IntegerField()),
                ('task_desc', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='TaskTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(choices=[('perday', 'per day'), ('weekly', 'weekly'), ('monthly', 'monthly')], max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Task')),
            ],
        ),
    ]
