# Generated by Django 2.2.2 on 2020-02-22 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_task_tasktracker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mymodel',
        ),
    ]
